upgrade bin/get-missing to compare file hashes

diff --git a/bin/get-missing b/bin/get-missing
--- a/bin/get-missing
+++ b/bin/get-missing
@@ -1,17 +1,55 @@
 #!/bin/bash
 
-target="${1%/}"
-source="${2%/}"
+source="${1%/}"
+target="${2%/}"
+
+if [[ -z "$source" || -z "$target" || -n "$3" ]]
+then
+  echo "Please provide exactly 2 arguments"
+  echo " 1: The path to the target dir to compare against"
+  echo " 2: The path to the source dir to be compared"
+  exit
+fi
+
+if [[ ! -d "$source" ]]
+then echo "Source $source is not a directory" && exit
+fi
+
+if [[ ! -d "$target" ]]
+then echo "Target $target is not a directory" && exit
+fi
 
 echo "Finding files in $source that are not in $target"
 
-target_files="$(find "$target" -type f)"
-source_files="$(find "$source" -type f)"
+# Build index of all filenames + content hashes in target dir
+target_index=/tmp/get-missing-target-index
+output=/tmp/get-missing-output
+rm -rf "$output" "$target_index"
+touch "$output" "$target_index"
 
-for f in $source_files
+echo "Building an index of files in $target, this might take a little while.."
+while IFS= read -r -d "" f
 do
-  dup="$(echo "$target_files" | grep -o "$(basename "$f")")"
-  if [[ -z "$dup" ]]
-  then echo "$f is not present in $target"
+  if [[ -f "$f" ]]
+  then echo "$(sha256sum "$f" | head -c64) $(basename "$f")" >> $target_index
   fi
-done
+done < <(find "$target" -print0 -type f)
+
+echo "Scanning $source for files that aren't in the target index.."
+while IFS= read -r -d "" f
+do
+  if [[ -f "$f" ]]
+  then
+    source_f="$(sha256sum "$f" | head -c64) $f"
+    if ! grep -qs "$(basename "$source_f")" "$target_index"
+    then echo "$source_f does NOT exist in $target" >> "$output"
+    fi
+  fi
+done < <(find "$source" -print0 -type f)
+
+if [[ "$(wc -c < "$output")" != "0" ]]
+then
+  echo "Missing files:"
+  cat "$output"
+else echo "There are not any files in $source that aren't also in $target :)"
+fi
