fix md-to-pdf util

diff --git a/bin/md-to-pdf b/bin/md-to-pdf
--- a/bin/md-to-pdf
+++ b/bin/md-to-pdf
@@ -1,9 +1,12 @@
 #!/bin/bash
 
+function err { >&2 echo "Error: $1"; exit 1; }
+
 pandoc   --version &> /dev/null || err "install pandoc"
 pdflatex --version &> /dev/null || err "install texlive-latex-recommended and texlive-fonts-recommended"
 
 input="$1"
+output="$2"
 
 if [[ ! -f "$input" ]]
 then echo "Can't find input file at $input" && exit
@@ -13,4 +16,4 @@ if [[ -f "$output" ]]
 then echo "Output file at $output already exists" && exit
 fi
 
-cat "$input" | pandoc -f markdown -t latex -V geometry:margin=1in --pdf-engine=xelatex -o "$output"
+pandoc "$input" -f markdown -t latex -V geometry:margin=1in --pdf-engine=xelatex -o "$output"
